import type { BuilderSection, ResumeData, ResumeTemplate } from "../types/resume";

export const resumeTemplates: ResumeTemplate[] = [
  {
    id: "standard",
    renderer: "analyst",
    name: "Professional",
    eyebrow: "Project led",
    description:
      "A dense, evidence-led format for skills, projects, certifications, and high-impact experience.",
    accent: "#202020",
    background: "#efefec",
    suitableFor: "Most roles and ATS applications",
    layout: "single",
    supportsPhoto: false,
    sections: [
      "basics",
      "summary",
      "skills",
      "experience",
      "projects",
      "certifications",
      "education",
    ],
    sidebarSections: [],
    audience: "experienced",
    popular: true,
  },
  {
    id: "minimal",
    renderer: "column",
    name: "Modern ATS",
    eyebrow: "Structured",
    description: "A restrained two-column format with clear hierarchy and readable sections.",
    accent: "#242a29",
    background: "#eceeeb",
    suitableFor: "Business, operations and product",
    layout: "sidebar",
    supportsPhoto: false,
    sections: ["basics", "summary", "skills", "education", "projects", "experience"],
    sidebarSections: ["skills", "education", "projects"],
    audience: "experienced",
    popular: true,
  },
  {
    id: "terminal",
    renderer: "blueprint",
    name: "Technical",
    eyebrow: "Engineering",
    description: "A skills-forward technical resume with room for impact, systems, and projects.",
    accent: "#244b44",
    background: "#e6eeeb",
    suitableFor: "Software, data and infrastructure",
    layout: "sidebar",
    supportsPhoto: false,
    sections: ["basics", "summary", "experience", "education", "projects", "skills"],
    sidebarSections: ["projects", "skills"],
    audience: "experienced",
    popular: true,
  },
  {
    id: "analyst",
    renderer: "chronological",
    name: "Data Analyst",
    eyebrow: "Reverse chronological",
    description:
      "A conventional one-page format for analytics skills and experience presented newest first.",
    accent: "#243d36",
    background: "#e9eeeb",
    suitableFor: "Data, business intelligence and analytics",
    layout: "single",
    supportsPhoto: false,
    sections: ["basics", "summary", "experience", "education", "skills", "projects"],
    sidebarSections: [],
    audience: "fresher",
    popular: true,
  },
  {
    id: "compact",
    renderer: "compact",
    name: "Compact Pro",
    eyebrow: "Dense one page",
    description: "A space-efficient format for a substantial career without visual clutter.",
    accent: "#315f54",
    background: "#eceeea",
    suitableFor: "Senior specialists and consultants",
    layout: "sidebar",
    supportsPhoto: false,
    sections: ["basics", "summary", "experience", "projects", "skills", "education"],
    sidebarSections: ["skills", "education"],
    audience: "experienced",
    popular: true,
  },
  {
    id: "finance",
    renderer: "finance",
    name: "Finance",
    eyebrow: "Metrics led",
    description:
      "A conservative finance format built around scope, decisions, and measurable results.",
    accent: "#254d45",
    background: "#e9eeeb",
    suitableFor: "Finance, accounting and investment",
    layout: "single",
    supportsPhoto: false,
    sections: ["basics", "summary", "experience", "skills", "projects", "education"],
    sidebarSections: [],
    audience: "experienced",
  },
  {
    id: "healthcare",
    renderer: "healthcare",
    name: "Healthcare",
    eyebrow: "Clinical operations",
    description: "A calm, structured resume for patient care, quality, and health operations.",
    accent: "#24706b",
    background: "#e6f0ee",
    suitableFor: "Healthcare, clinical and public health",
    layout: "sidebar",
    supportsPhoto: false,
    sections: ["basics", "summary", "experience", "projects", "skills", "education"],
    sidebarSections: ["skills", "education"],
    audience: "experienced",
  },
  {
    id: "sales",
    renderer: "sales",
    name: "Sales Impact",
    eyebrow: "Revenue",
    description:
      "A commercial resume that gives targets, growth, and customer wins clear priority.",
    accent: "#8a4d2e",
    background: "#f1ebe7",
    suitableFor: "Sales, partnerships and revenue",
    layout: "sidebar",
    supportsPhoto: false,
    sections: ["basics", "summary", "experience", "projects", "skills", "education"],
    sidebarSections: ["projects", "skills", "education"],
    audience: "experienced",
  },
  {
    id: "executive",
    renderer: "summit",
    name: "Executive",
    eyebrow: "Leadership",
    description: "A leadership-focused document with an optional professional portrait rail.",
    accent: "#203b57",
    background: "#e6ecf2",
    suitableFor: "Directors, executives and global roles",
    layout: "sidebar",
    supportsPhoto: true,
    photoShape: "circle",
    sections: ["basics", "summary", "experience", "education", "projects", "skills"],
    sidebarSections: ["projects", "skills"],
    audience: "experienced",
  },
  {
    id: "classic",
    renderer: "editorial",
    name: "Academic",
    eyebrow: "Formal",
    description: "A typography-led format for research, policy, legal, and academic work.",
    accent: "#424242",
    background: "#f2f0eb",
    suitableFor: "Academia, research, law and policy",
    layout: "single",
    supportsPhoto: false,
    sections: ["basics", "summary", "experience", "education", "projects", "skills"],
    sidebarSections: [],
    audience: "experienced",
  },
  {
    id: "hybrid",
    renderer: "hybrid",
    name: "Skills First",
    eyebrow: "Functional hybrid",
    description: "Transferable skills and selected proof lead before work history.",
    accent: "#5a516d",
    background: "#eceeea",
    suitableFor: "Specialists and career transitions",
    layout: "single",
    supportsPhoto: false,
    sections: ["basics", "summary", "skills", "projects", "experience", "education"],
    sidebarSections: [],
    audience: "career-change",
  },
  {
    id: "career-change",
    renderer: "pivot",
    name: "Career Pivot",
    eyebrow: "Transferable impact",
    description: "Relevant capabilities and evidence reframe an established work history.",
    accent: "#79515e",
    background: "#eceeea",
    suitableFor: "Career changers and returners",
    layout: "sidebar",
    supportsPhoto: false,
    sections: ["basics", "summary", "skills", "projects", "experience", "education"],
    sidebarSections: ["skills", "education"],
    audience: "career-change",
  },
  {
    id: "fresher",
    renderer: "fresher",
    name: "Graduate",
    eyebrow: "No experience needed",
    description: "Education, projects, and practical skills lead with no experience section.",
    accent: "#326b57",
    background: "#e9eeeb",
    suitableFor: "Graduates and entry-level candidates",
    layout: "single",
    supportsPhoto: false,
    sections: ["basics", "summary", "education", "projects", "skills"],
    sidebarSections: [],
    audience: "fresher",
    popular: true,
  },
  {
    id: "internship",
    renderer: "first-step",
    name: "Internship",
    eyebrow: "Student",
    description: "Coursework, projects, and campus leadership form a credible first resume.",
    accent: "#3f6591",
    background: "#eceeea",
    suitableFor: "Students and internship seekers",
    layout: "sidebar",
    supportsPhoto: false,
    sections: ["basics", "summary", "education", "skills", "projects"],
    sidebarSections: ["education", "skills"],
    audience: "fresher",
  },
  {
    id: "nova",
    renderer: "meridian",
    name: "International",
    eyebrow: "Photo optional",
    description: "A modern international CV with a portrait, profile, and supporting detail rail.",
    accent: "#28785b",
    background: "#e7f2eb",
    suitableFor: "Global markets where photos are expected",
    layout: "sidebar",
    supportsPhoto: true,
    photoShape: "rounded",
    sections: ["basics", "summary", "experience", "projects", "skills", "education"],
    sidebarSections: ["projects", "skills", "education"],
    audience: "experienced",
  },
  {
    id: "studio",
    renderer: "horizon",
    name: "Contemporary",
    eyebrow: "Photo optional",
    description: "An airy, polished CV with a portrait and an original curved masthead.",
    accent: "#347fb7",
    background: "#e8f2fa",
    suitableFor: "Education, research and creative roles",
    layout: "sidebar",
    supportsPhoto: true,
    photoShape: "rounded",
    sections: ["basics", "summary", "experience", "projects", "skills", "education"],
    sidebarSections: ["projects", "skills", "education"],
    audience: "experienced",
  },
];

export const builderSections: {
  id: BuilderSection;
  label: string;
  shortLabel: string;
}[] = [
  { id: "basics", label: "Personal details", shortLabel: "Details" },
  { id: "summary", label: "Professional summary", shortLabel: "Summary" },
  { id: "experience", label: "Work experience", shortLabel: "Experience" },
  { id: "education", label: "Education", shortLabel: "Education" },
  { id: "projects", label: "Selected projects", shortLabel: "Projects" },
  { id: "skills", label: "Skills & tools", shortLabel: "Skills" },
  {
    id: "certifications",
    label: "Awards & certifications",
    shortLabel: "Awards",
  },
];
